# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [5]:
import numpy

#### Q2 : Afficher la version de numpy et la configuration 

In [6]:
numpy.version.version

'1.20.2'

#### Q3 : Créer un vecteur nul de taille 10

In [16]:
# vector = numpy.empty(10)
# utilisation de zeros pour faciliter la lecture
vector = numpy.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [15]:
numpy.put(vector, [4], [1])
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [27]:
# Z = numpy.full(40, [i for i in range(10, 50, 1)])
Z = numpy.arange(10, 50, 1)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [34]:
Z = numpy.flipud(Z)
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [49]:
# mat = numpy.full((3,3), [i for i in range(0, 8, 1)])
mat = numpy.arange(0,9,1).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [41]:
identity = numpy.identity(3, int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [57]:
rand = numpy.random.randint(0, 50, 27).reshape(3,3,3)
rand

array([[[30, 23, 17],
        [31, 45, 31],
        [45, 25, 12]],

       [[47, 12,  6],
        [11, 31, 19],
        [22, 24,  2]],

       [[22, 46, 23],
        [34, 45, 44],
        [ 4,  7, 22]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [65]:
mat10 = numpy.random.randint(0,50,100).reshape(10,10)
print(mat10)
print(numpy.amax(mat10))
print(numpy.amin(mat10))

[[32 23 39 11  7 18 44  6 17 37]
 [ 0 27 34 20  8 14 39 27 31 25]
 [15 43 46  9 25 25 23 29 37 44]
 [32 35  1  5 18 14 15 43 44 23]
 [16 32 14 35 27 21 18 46 41 47]
 [10 11 24  9 40  4 17 40  7 14]
 [ 2 22  4 17 32 39 39 32 49 13]
 [34 24 36 42  3 16 49  4 27 21]
 [24 14  8 42 28 25 35 38  6 30]
 [27 13  3  9 10 49 33 44 48 40]]
49
0


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [ ]:
mat5 = 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [70]:
liste = numpy.random.randint(0,50,5)
print(liste)
print(liste.sum())

[29 18 20  5 13]
85


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [75]:
liste2 = numpy.random.randint(0,50,5)
print(liste2)
print(numpy.average(liste2))

[11 41 18 28 24]
24.4


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [79]:
l = [x for x in range(11)]
print(l)
print(numpy.size(l))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [84]:
# tab10 = numpy.random.random(10)
tab10 = numpy.arange(0,1,0.1)
tab10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [88]:
A = numpy.arange(0,5,1)
B = numpy.arange(0,5,1)
numpy.array_equal(A, B)

True

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [90]:
floatToInt = numpy.random.uniform(0,10,10)
floatToInt = numpy.int32(floatToInt)
floatToInt

array([1, 8, 4, 3, 5, 6, 5, 2, 9, 0])

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [93]:
M = numpy.random.randint(0,50,4).reshape(2,2)
M

array([[49, 29],
       [20, 25]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)