In [40]:
import numpy as np
import random

# Quelques fonctions utiles

On a créé un tableau 2D contenant des valeurs aléatoires. 

In [41]:
rand = np.random.randint(0, 50, 4).reshape(2,2)
rand

array([[19,  3],
       [38,  6]])

Donner le type de la variable rdm_mat

In [42]:
type(rand)

numpy.ndarray

Donner la somme des éléments de ce tableau 2D

In [43]:
np.sum(rand)

66

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [44]:
np.max(rand, axis=1)

array([19, 38])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [45]:
np.max(rand, axis=0)

array([38,  6])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

In [46]:
mat = []
for i in range(0, 5, 1):
    line = []
    for j in range (0, 5, 1):
        line.append(j)
    mat.append(line)
    
np.max(mat, axis=1)

array([4, 4, 4, 4, 4])

Créer un vecteur aléatoire de taille 100

In [48]:
vec = np.random.randint(0, 100, 100)
vec.shape

(100,)

Récupérer la position de la valeur maximale du vecteur 

In [49]:
np.argmax(vec)

14

Afficher cette valeur 

In [50]:
vec[np.argmax(vec)]

99

Convertir le vecteur en un tableau 10, 10

In [55]:
matFromVec = np.reshape(vec, (10,10))
matFromVec

array([[17, 13, 23, 10, 33, 88, 91, 55, 58, 66],
       [40, 62, 58, 24, 99, 70, 20, 17, 23, 19],
       [ 6, 21, 78, 77,  3, 57, 79, 98, 59, 78],
       [47, 34, 57, 86, 61, 63,  6, 73, 90, 64],
       [34, 90, 15, 94, 32, 10, 56, 27, 28, 61],
       [ 7, 96, 17, 16,  9, 69, 57,  2, 32, 93],
       [99, 61, 97, 70, 26, 39,  1, 41, 40, 73],
       [32, 34, 84, 72, 10, 52,  1, 25, 10, 90],
       [57, 15, 88, 80, 80, 82, 31, 10, 15, 74],
       [33, 33, 52, 33, 98, 67, 34, 49, 85, 32]])

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [57]:
averages = np.average(matFromVec, axis=1)
averages

array([45.4, 43.2, 55.6, 58.1, 44.7, 39.8, 54.7, 41. , 53.2, 51.6])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [58]:
np.sum(matFromVec, axis=0)

array([372, 459, 569, 562, 451, 597, 376, 397, 440, 650])

Calculer la somme pour chaque ligne (sans boucles)

In [59]:
np.sum(matFromVec, axis=1)

array([454, 432, 556, 581, 447, 398, 547, 410, 532, 516])